# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maticbratina/code/opengl-renderer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maticbratina/code/opengl-renderer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maticbratina/code/opengl-renderer/CMakeFiles /home/maticbratina/code/opengl-renderer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maticbratina/code/opengl-renderer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/GLFW3/src/CMakeFiles/glfw.dir/build.make thirdparty/GLFW3/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/GLFW3/src/CMakeFiles/update_mappings.dir/build.make thirdparty/GLFW3/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/glad/CMakeFiles/glad.dir/build.make thirdparty/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named stb_image

# Build rule for target.
stb_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image
.PHONY : stb_image

# fast build rule for target.
stb_image/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/stb_image/CMakeFiles/stb_image.dir/build.make thirdparty/stb_image/CMakeFiles/stb_image.dir/build
.PHONY : stb_image/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/imgui/CMakeFiles/imgui.dir/build.make thirdparty/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/Assimp/code/CMakeFiles/assimp.dir/build.make thirdparty/Assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/CameraController.o: src/CameraController.cpp.o
.PHONY : src/CameraController.o

# target to build an object file
src/CameraController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/CameraController.cpp.o
.PHONY : src/CameraController.cpp.o

src/CameraController.i: src/CameraController.cpp.i
.PHONY : src/CameraController.i

# target to preprocess a source file
src/CameraController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/CameraController.cpp.i
.PHONY : src/CameraController.cpp.i

src/CameraController.s: src/CameraController.cpp.s
.PHONY : src/CameraController.s

# target to generate assembly for a file
src/CameraController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/CameraController.cpp.s
.PHONY : src/CameraController.cpp.s

src/Core/Core.o: src/Core/Core.cpp.o
.PHONY : src/Core/Core.o

# target to build an object file
src/Core/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Core.cpp.o
.PHONY : src/Core/Core.cpp.o

src/Core/Core.i: src/Core/Core.cpp.i
.PHONY : src/Core/Core.i

# target to preprocess a source file
src/Core/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Core.cpp.i
.PHONY : src/Core/Core.cpp.i

src/Core/Core.s: src/Core/Core.cpp.s
.PHONY : src/Core/Core.s

# target to generate assembly for a file
src/Core/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Core.cpp.s
.PHONY : src/Core/Core.cpp.s

src/Core/Framebuffer.o: src/Core/Framebuffer.cpp.o
.PHONY : src/Core/Framebuffer.o

# target to build an object file
src/Core/Framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Framebuffer.cpp.o
.PHONY : src/Core/Framebuffer.cpp.o

src/Core/Framebuffer.i: src/Core/Framebuffer.cpp.i
.PHONY : src/Core/Framebuffer.i

# target to preprocess a source file
src/Core/Framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Framebuffer.cpp.i
.PHONY : src/Core/Framebuffer.cpp.i

src/Core/Framebuffer.s: src/Core/Framebuffer.cpp.s
.PHONY : src/Core/Framebuffer.s

# target to generate assembly for a file
src/Core/Framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Framebuffer.cpp.s
.PHONY : src/Core/Framebuffer.cpp.s

src/Core/ShaderProgram.o: src/Core/ShaderProgram.cpp.o
.PHONY : src/Core/ShaderProgram.o

# target to build an object file
src/Core/ShaderProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/ShaderProgram.cpp.o
.PHONY : src/Core/ShaderProgram.cpp.o

src/Core/ShaderProgram.i: src/Core/ShaderProgram.cpp.i
.PHONY : src/Core/ShaderProgram.i

# target to preprocess a source file
src/Core/ShaderProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/ShaderProgram.cpp.i
.PHONY : src/Core/ShaderProgram.cpp.i

src/Core/ShaderProgram.s: src/Core/ShaderProgram.cpp.s
.PHONY : src/Core/ShaderProgram.s

# target to generate assembly for a file
src/Core/ShaderProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/ShaderProgram.cpp.s
.PHONY : src/Core/ShaderProgram.cpp.s

src/Core/Texture.o: src/Core/Texture.cpp.o
.PHONY : src/Core/Texture.o

# target to build an object file
src/Core/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Texture.cpp.o
.PHONY : src/Core/Texture.cpp.o

src/Core/Texture.i: src/Core/Texture.cpp.i
.PHONY : src/Core/Texture.i

# target to preprocess a source file
src/Core/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Texture.cpp.i
.PHONY : src/Core/Texture.cpp.i

src/Core/Texture.s: src/Core/Texture.cpp.s
.PHONY : src/Core/Texture.s

# target to generate assembly for a file
src/Core/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Core/Texture.cpp.s
.PHONY : src/Core/Texture.cpp.s

src/MainLayer.o: src/MainLayer.cpp.o
.PHONY : src/MainLayer.o

# target to build an object file
src/MainLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/MainLayer.cpp.o
.PHONY : src/MainLayer.cpp.o

src/MainLayer.i: src/MainLayer.cpp.i
.PHONY : src/MainLayer.i

# target to preprocess a source file
src/MainLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/MainLayer.cpp.i
.PHONY : src/MainLayer.cpp.i

src/MainLayer.s: src/MainLayer.cpp.s
.PHONY : src/MainLayer.s

# target to generate assembly for a file
src/MainLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/MainLayer.cpp.s
.PHONY : src/MainLayer.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Model.o: src/Model.cpp.o
.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i
.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s
.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... update_mappings"
	@echo "... app"
	@echo "... assimp"
	@echo "... glad"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... stb_image"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/CameraController.o"
	@echo "... src/CameraController.i"
	@echo "... src/CameraController.s"
	@echo "... src/Core/Core.o"
	@echo "... src/Core/Core.i"
	@echo "... src/Core/Core.s"
	@echo "... src/Core/Framebuffer.o"
	@echo "... src/Core/Framebuffer.i"
	@echo "... src/Core/Framebuffer.s"
	@echo "... src/Core/ShaderProgram.o"
	@echo "... src/Core/ShaderProgram.i"
	@echo "... src/Core/ShaderProgram.s"
	@echo "... src/Core/Texture.o"
	@echo "... src/Core/Texture.i"
	@echo "... src/Core/Texture.s"
	@echo "... src/MainLayer.o"
	@echo "... src/MainLayer.i"
	@echo "... src/MainLayer.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

